#!/bin/bash

set -e

file="$1"

[ -f "FPKGBUILD" ] && {
  file="$PWD/FPKGBUILD"
}

[ -n "$1" ] || [ -f "FPKGBUILD" ] || {
  echo "Please specify an FPKGBUILD file"
  exit 1
}

[ -f "$file" ] || {
  echo "File $file does not exist!"
  exit 1
}

set -u

file="$(readlink -f "$file")"

source "$file"

pkgdir="$(mktemp -d)"
tmp_dir="$(mktemp -d)"
oldpwd="$(pwd)"
mkdir -p "$pkgdir"

trap 'exit_handling' EXIT

function exit_handling() {
  # error handling goes here
  [ -n "$pkgdir" ] && rm -rf "$pkgdir"
  [ -n "$tmp_dir" ] && rm -rf "$tmp_dir"
}

cd "$tmp_dir"

for x in "${sources[@]}"; do
  wget -q --show-progress "$x"
done

if [[ -v USE_HOST_TOOLS ]]; then
  build
else
  fpkg run-multi bash coreutils "${makedepends[@]}" <<EOF
set -e
set -u

source "$file"
pkgdir="$pkgdir"
oldpwd="$oldpwd"

build
EOF
fi
cd "$oldpwd"

# Now the package is installed to pkgdir

function deps_to_string() {
  for x in "${depends[@]}"; do
    name="$(echo -n "$x" | grep -E -o "^[a-ZA-Z\-_1-9]+")"
    version="$(echo -n "$x" | grep -P -o "(?<=$name).*")"
    echo "depends \"${name}\" $(if [ -n "$version" ]; then echo "version=\"$version\""; fi)"
  done
}

mkdir -p "$pkgdir/fpkg"
cat <<EOF >"$pkgdir/fpkg/pkg.kdl"
name "$pkgname"
version "$pkgver"

$(deps_to_string)
EOF

echo "----------------------"
cat "$pkgdir/fpkg/pkg.kdl"
echo "----------------------"

fpkg gen-pkg "$pkgdir" "$pkgname-$pkgver.fpkg"
exit 0
