#!/bin/bash

set -e

file="$1"

[ -f "FPKGBUILD" ] && {
  file="FPKGBUILD"
}

[ -n "$1" ] || [ -f "FPKGBUILD" ] || {
  echo "Please specify an FPKGBUILD file"
  exit 1
}

[ -f "$file" ] || {
  echo "File $file does not exist!"
  exit 1
}

source "$file"

pkgdir="$(mktemp -d)"
tmp_dir="$(mktemp -d)"
old_pwd="$(pwd)"
mkdir -p "$pkgdir"

cd "$tmp_dir"
build
cd "$old_pwd"

# Now the package is installed to pkgdir

function deps_to_string() {
  for x in "${depends[@]}"; do
    name="$(echo -n "$x" | grep -E -o "^[a-ZA-Z\-_1-9]+")"
    version="$(echo -n "$x" | grep -P -o "(?<=$name).*")"
    echo "depends \"${name}\" $(if [ -n "$version" ]; then echo "version=\"$version\""; fi)"
  done
}

mkdir -p "$pkgdir/fpkg"
cat <<EOF >"$pkgdir/fpkg/pkg.kdl"
name "$pkgname"
version "$pkgver"

$(deps_to_string)
EOF

cat "$pkgdir/fpkg/pkg.kdl"

fpkg gen-pkg "$pkgdir" "$pkgname-$pkgver.fpkg"
exit 0
