name: Rust
run-name: Rust

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: fpkg
        path: target/release/fpkg
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.7
