name: Rust
run-name: Rust

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Dependencies
        run: |
          sudo apt-get update --yes && sudo apt-get install --yes musl-tools
          rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: |
          cargo build --release --verbose
          strip -s target/x86_64-unknown-linux-musl/release/fpkg
      - name: Test
        run: cargo test --verbose --release
      - uses: actions/upload-artifact@v4
        with:
          name: fpkg
          path: target/x86_64-unknown-linux-musl/release/fpkg
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download fpkg
        uses: actions/download-artifact@v4
        with:
          name: fpkg
          path: fpkg
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fpkg/fpkg
          body_path: CHANGELOG.md
