name: Rust
run-name: Rust

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Dependencies
        run: |
          sudo apt-get update --yes && sudo apt-get install --yes musl-tools
          rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: |
          cargo build --release --verbose
          strip -s target/x86_64-unknown-linux-musl/release/fpkg
      - name: Test
        run: cargo test --verbose --release
      - uses: actions/upload-artifact@v4
        with:
          name: fpkg
          path: target/x86_64-unknown-linux-musl/release/fpkg
      - name: Generate the changelog
        uses: orhun/git-cliff-action@v4
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          files: target/x86_64-unknown-linux-musl/release/fpkg
          draft: true
          body_path: CHANGELOG.md
